
[functions.revenuecat_webhook]
enabled = true
verify_jwt = false
import_map = "./functions/revenuecat_webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/revenuecat_webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/revenuecat_webhook/*.html" ]
[functions.ai_summary]
enabled = true
verify_jwt = false